/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import classes.Cliente;
import classes.Pedido;
import classes.Pizza;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static view.TelaInicial.pizzas;
import static view.TelaInicial.clientes;
import static view.TelaInicial.pedidos;

/**
 *
 * @author deivi
 */
public class TelaCadastraPedido2 extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastraPedido2
     */
    
    public JFrame telaFuncionario;
    public static String filePath;

    public TelaCadastraPedido2(JFrame telaFuncionario) {
        initComponents();
        setLocationRelativeTo(null); // Centraliza a janela na tela
        setResizable(false); // Desabilita o redimensionamento da janela
        this.filePath = "";
        this.telaFuncionario = telaFuncionario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnVoltarInicial1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Cadastro Pedido");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 60, -1, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel6.setText("Telefone do cliente:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel7.setText("Código da pizza: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, -1));

        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 137, -1));

        txtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneActionPerformed(evt);
            }
        });
        getContentPane().add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 137, -1));

        btnCadastrar.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, -1, -1));

        btnVoltarInicial1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btnVoltarInicial1.setText("Voltar");
        btnVoltarInicial1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarInicial1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltarInicial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, -1, -1));

        jButton3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jButton3.setText("Tela Pedido");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoRedimensionada25.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 790, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneActionPerformed

    private boolean verificaClienteExistente(String telefone) {
        // Verificar se o número de telefone existe na lista de clientes cadastrados
        for (Cliente cliente: clientes) {
            if (cliente.getTelefone().equals(telefone)) {
                return true;
            }
        }
        return false;
    }
    
    private boolean verificaPizzaExistente(String codigoPizza) {
        // Verificar se o código da pizza existe na lista de pizzas cadastradas
        for (Pizza pizza : pizzas) {
            if (pizza.getCodigo().equals(codigoPizza)) {
                return true;
            }
        }
        return false;
    }
    
    private String directoryPath;
    
    // Método para criar ou atualizar o arquivo de clientes
    private void criarOuAtualizarArquivoPedidos(Pedido pedido, String filePath) {
            try {
                FileWriter fw = new FileWriter(filePath, true); // O true no construtor FileWriter indica que iremos adicionar ao final do arquivo
                BufferedWriter bw = new BufferedWriter(fw);

                // Escrevendo os dados do novo pedido no arquivo
                bw.write("Número do pedido: " + pedido.getNumPedido() + ", Telefone do Cliente: " + pedido.getTelefone() + ", Código da Pizza: " + pedido.getCodigoPizza() + ", Estado do Pedido: " + pedido.getEstado());
                bw.newLine(); // Adiciona uma nova linha para o novo pedido

                bw.close(); // Fecha o BufferedWriter
                fw.close(); // Fecha o FileWriter

                System.out.println("Arquivo pedidos.txt atualizado com sucesso em: " + filePath);
            } catch (IOException e) {
                System.err.println("Erro ao atualizar o arquivo pedidos.txt: " + e.getMessage());
            }
     }
    
    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        
        String codigo = txtCodigo.getText(); // Obtenha o texto do campo txtCodigo
        String telefone = txtTelefone.getText();
        String codigoPizza = txtCodigo.getText();

        // Verificar se o número de telefone e o código da pizza existem
        boolean clienteExiste = verificaClienteExistente(telefone);
        boolean pizzaExiste = verificaPizzaExistente(codigoPizza);

        if (!clienteExiste) {
            JOptionPane.showMessageDialog(this, "Cliente não encontrado!", "Erro", JOptionPane.ERROR_MESSAGE);
        } else if (!pizzaExiste) {
            JOptionPane.showMessageDialog(this, "Código de pizza não encontrado!", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            // Se o cliente e a pizza existirem, o pedido pode ser registrado
            // Código para registrar o pedido...

            try {
                classes.Global.numPedido++;
                Pedido pedido = new Pedido(Integer.toString(classes.Global.numPedido), telefone, codigo);
                TelaInicial.adicionaPedido(pedido);
                
                // Se o diretório ainda não foi selecionado, solicita ao usuário que escolha o diretório para salvar o arquivo
                if (directoryPath == null || directoryPath.isEmpty()) {
                    JFileChooser fileChooser = new JFileChooser();
                    fileChooser.setDialogTitle("Salvar arquivo de pedidos");
                    fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

                    // Exibe o seletor de diretório
                    int userSelection = fileChooser.showSaveDialog(this);

                    if (userSelection == JFileChooser.APPROVE_OPTION) {
                        // Obtém o diretório selecionado pelo usuário
                        directoryPath = fileChooser.getSelectedFile().getAbsolutePath();
                    } else {
                        // Se o usuário cancelar a seleção do diretório, retorna sem fazer nada
                        return;
                    }
                }
                
                // Caminho completo para o arquivo de pedidos
                filePath = directoryPath + "/pedidos.txt";
                
                // Adiciona a nova pizza ao arquivo
                criarOuAtualizarArquivoPedidos(pedido, filePath);
         
                // Limpar os campos após o cadastro
                txtCodigo.setText("");
                txtTelefone.setText("");

            } catch (IllegalArgumentException e) {
                switch (e.getMessage()) {
                    case "Número do pedido inválido":
                        JOptionPane.showMessageDialog(this, "Número do pedido inválido!", "Erro", JOptionPane.ERROR_MESSAGE);
                        break;
                    case "Telefone inválido":
                        JOptionPane.showMessageDialog(this, "Digite um telefone válido!", "Erro", JOptionPane.ERROR_MESSAGE);
                        break;
                    case "Código inválido":
                        JOptionPane.showMessageDialog(this, "Digite um código válido!", "Erro", JOptionPane.ERROR_MESSAGE);
                        break;
                    default:
                        break;
                }
            }
            
            JOptionPane.showMessageDialog(this, "Pedido registrado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        }

        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnVoltarInicial1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarInicial1ActionPerformed
        this.setVisible(false);
        telaFuncionario.setVisible(true);
    }//GEN-LAST:event_btnVoltarInicial1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        TelaPedido telaPedido = new TelaPedido(this, pedidos);
        this.setVisible(false);
        telaPedido.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastraPedido2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastraPedido2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastraPedido2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastraPedido2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastraPedido2(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnVoltarInicial1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
